import type { Deal } from '@/types';

// ============================================================
// MOCK DATA — Swap with real API later by changing this file
// Images: Unsplash free-to-use
// ============================================================

export const MOCK_DEALS: Deal[] = [
  // ── FLIGHTS ──────────────────────────────────────────────
  {
    id: 'fl-cgk-dps-001',
    productType: 'flight',
    title: 'Jakarta → Bali',
    destination: 'Bali',
    destinationCode: 'DPS',
    origin: 'Jakarta',
    originCode: 'CGK',
    country: 'Indonesia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    price: 549000,
    currency: 'IDR',
    affiliateUrl: 'https://www.traveloka.com/en-id/flight',
    affiliatePartner: 'Traveloka',
    departureDate: '2025-12-20',
    returnDate: '2025-12-25',
    duration: '1h 30m',
    airline: 'Lion Air',
    stops: 0,
  },
  {
    id: 'fl-cgk-sin-002',
    productType: 'flight',
    title: 'Jakarta → Singapore',
    destination: 'Singapore',
    destinationCode: 'SIN',
    origin: 'Jakarta',
    originCode: 'CGK',
    country: 'Singapore',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80',
    price: 1250000,
    currency: 'IDR',
    affiliateUrl: 'https://www.tiket.com/pesawat',
    affiliatePartner: 'Tiket.com',
    departureDate: '2026-01-10',
    returnDate: '2026-01-15',
    duration: '2h 10m',
    airline: 'Garuda Indonesia',
    stops: 0,
  },
  {
    id: 'fl-cgk-bkk-003',
    productType: 'flight',
    title: 'Jakarta → Bangkok',
    destination: 'Bangkok',
    destinationCode: 'BKK',
    origin: 'Jakarta',
    originCode: 'CGK',
    country: 'Thailand',
    image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&q=80',
    price: 1800000,
    currency: 'IDR',
    affiliateUrl: 'https://www.airasia.com',
    affiliatePartner: 'AirAsia',
    departureDate: '2026-02-14',
    returnDate: '2026-02-21',
    duration: '3h 30m',
    airline: 'AirAsia',
    stops: 0,
  },
  {
    id: 'fl-cgk-kul-004',
    productType: 'flight',
    title: 'Jakarta → Kuala Lumpur',
    destination: 'Kuala Lumpur',
    destinationCode: 'KUL',
    origin: 'Jakarta',
    originCode: 'CGK',
    country: 'Malaysia',
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80',
    price: 890000,
    currency: 'IDR',
    affiliateUrl: 'https://www.airasia.com',
    affiliatePartner: 'AirAsia',
    departureDate: '2026-01-25',
    duration: '2h 20m',
    airline: 'AirAsia',
    stops: 0,
  },
  {
    id: 'fl-cgk-nrt-005',
    productType: 'flight',
    title: 'Jakarta → Tokyo',
    destination: 'Tokyo',
    destinationCode: 'NRT',
    origin: 'Jakarta',
    originCode: 'CGK',
    country: 'Japan',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
    price: 5200000,
    currency: 'IDR',
    affiliateUrl: 'https://www.traveloka.com/en-id/flight',
    affiliatePartner: 'Traveloka',
    departureDate: '2026-03-20',
    returnDate: '2026-03-30',
    duration: '7h 45m',
    airline: 'Garuda Indonesia',
    stops: 0,
  },
  {
    id: 'fl-cgk-hkg-006',
    productType: 'flight',
    title: 'Jakarta → Hong Kong',
    destination: 'Hong Kong',
    destinationCode: 'HKG',
    origin: 'Jakarta',
    originCode: 'CGK',
    country: 'China SAR',
    image: 'https://images.unsplash.com/photo-1506148604580-8ca5c1d8c32c?w=800&q=80',
    price: 2900000,
    currency: 'IDR',
    affiliateUrl: 'https://www.tiket.com/pesawat',
    affiliatePartner: 'Tiket.com',
    departureDate: '2026-02-01',
    returnDate: '2026-02-07',
    duration: '4h 30m',
    airline: 'Cathay Pacific',
    stops: 0,
  },

  // ── HOTELS ───────────────────────────────────────────────
  {
    id: 'ht-bali-001',
    productType: 'hotel',
    title: 'The Mulia Bali',
    destination: 'Bali',
    destinationCode: 'DPS',
    country: 'Indonesia',
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
    price: 2100000,
    currency: 'IDR',
    affiliateUrl: 'https://www.agoda.com',
    affiliatePartner: 'Agoda',
    duration: '1 night',
    rating: 9.4,
    reviewCount: 2847,
    amenities: ['Pool', 'Beach', 'Spa', 'WiFi'],
  },
  {
    id: 'ht-bkk-001',
    productType: 'hotel',
    title: 'Capella Bangkok',
    destination: 'Bangkok',
    destinationCode: 'BKK',
    country: 'Thailand',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
    price: 3500000,
    currency: 'IDR',
    affiliateUrl: 'https://www.booking.com',
    affiliatePartner: 'Booking.com',
    duration: '1 night',
    rating: 9.6,
    reviewCount: 1253,
    amenities: ['Riverside', 'Pool', 'Fine Dining', 'Spa'],
  },
  {
    id: 'ht-sin-001',
    productType: 'hotel',
    title: 'Marina Bay Sands',
    destination: 'Singapore',
    destinationCode: 'SIN',
    country: 'Singapore',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=800&q=80',
    price: 5800000,
    currency: 'IDR',
    affiliateUrl: 'https://www.agoda.com',
    affiliatePartner: 'Agoda',
    duration: '1 night',
    rating: 9.1,
    reviewCount: 6742,
    amenities: ['Infinity Pool', 'Casino', 'Sky Park', 'WiFi'],
  },
  {
    id: 'ht-bali-002',
    productType: 'hotel',
    title: 'COMO Uma Seminyak',
    destination: 'Bali',
    destinationCode: 'DPS',
    country: 'Indonesia',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    price: 1750000,
    currency: 'IDR',
    affiliateUrl: 'https://www.traveloka.com/en-id/hotel',
    affiliatePartner: 'Traveloka',
    duration: '1 night',
    rating: 9.0,
    reviewCount: 980,
    amenities: ['Pool', 'Yoga', 'Spa', 'Restaurant'],
  },
  {
    id: 'ht-kul-001',
    productType: 'hotel',
    title: 'The RuMa Kuala Lumpur',
    destination: 'Kuala Lumpur',
    destinationCode: 'KUL',
    country: 'Malaysia',
    image: 'https://images.unsplash.com/photo-1596422846543-75c6fc197f07?w=800&q=80',
    price: 1400000,
    currency: 'IDR',
    affiliateUrl: 'https://www.booking.com',
    affiliatePartner: 'Booking.com',
    duration: '1 night',
    rating: 9.3,
    reviewCount: 752,
    amenities: ['Rooftop Pool', 'Gym', 'Fine Dining', 'WiFi'],
  },
  {
    id: 'ht-nrt-001',
    productType: 'hotel',
    title: 'Park Hyatt Tokyo',
    destination: 'Tokyo',
    destinationCode: 'NRT',
    country: 'Japan',
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80',
    price: 6200000,
    currency: 'IDR',
    affiliateUrl: 'https://www.agoda.com',
    affiliatePartner: 'Agoda',
    duration: '1 night',
    rating: 9.7,
    reviewCount: 2156,
    amenities: ['City View', 'Spa', 'Pool', 'Fine Dining'],
  },
];

// Normal price table — what partners usually charge
// (Used by insight engine to calculate real discounts)
export const NORMAL_PRICES: Record<string, number> = {
  'fl-cgk-dps-001': 950000,
  'fl-cgk-sin-002': 2100000,
  'fl-cgk-bkk-003': 2600000,
  'fl-cgk-kul-004': 1500000,
  'fl-cgk-nrt-005': 8500000,
  'fl-cgk-hkg-006': 4800000,
  'ht-bali-001':    3500000,
  'ht-bkk-001':     4800000,
  'ht-sin-001':     7200000,
  'ht-bali-002':    2500000,
  'ht-kul-001':     2200000,
  'ht-nrt-001':     9000000,
};

// ============================================================
// MOCK AI INSIGHTS
// ============================================================
export interface AIInsight {
  id: string;
  title: string;
  confidence: number;
  reason: string;
  urgency: string;
  urgencyLevel: 'high' | 'medium' | 'low';
}

export const MOCK_INSIGHTS: AIInsight[] = [
  {
    id: 'ins-001',
    title: '✈️ Jakarta → Singapore now 28% cheaper',
    confidence: 87,
    reason: 'Based on 3-year seasonal trend',
    urgency: 'Price may rise in 6 hours',
    urgencyLevel: 'high',
  },
  {
    id: 'ins-002',
    title: '🏨 Marina Bay Sands dropped 15% for next weekend',
    confidence: 92,
    reason: 'Historical flash sale pattern detected',
    urgency: 'Rare deal. Sells out quickly.',
    urgencyLevel: 'high',
  },
  {
    id: 'ins-003',
    title: '✈️ Jakarta → Tokyo flights are hitting 6-month lows',
    confidence: 76,
    reason: 'New route capacity added by airlines',
    urgency: 'Stable price. Book within 3 days.',
    urgencyLevel: 'low',
  },
  {
    id: 'ins-004',
    title: '🏨 The Mulia Bali is offering hidden free upgrades',
    confidence: 84,
    reason: 'Cross-referenced with recent Agoda bookings',
    urgency: 'Valid for next 24 hours',
    urgencyLevel: 'medium',
  },
  {
    id: 'ins-005',
    title: '✈️ Jakarta → Bangkok weekend flights down 20%',
    confidence: 89,
    reason: 'Airline price matching detected',
    urgency: 'Price may rise in 12 hours',
    urgencyLevel: 'medium',
  },
  {
    id: 'ins-006',
    title: '🏨 Capella Bangkok early bird rates are 30% below avg',
    confidence: 95,
    reason: 'Off-peak booking anomaly',
    urgency: 'Book now for Q4 travel',
    urgencyLevel: 'low',
  },
];
